#!/usr/bin/env bash

DEPLOY_BRANCH="gh-pages"

jekyll build

CURRENT_SHA=$(git log HEAD^..HEAD --format="%h")

git checkout -B gh-pages

git add -f _site/

git commit -m "update site from $CURRENT_SHA"

git push -f origin HEAD:$DEPLOY_BRANCH

git checkout -
